app:
  name: streamlink
  rel: 1
git:
  repo: https://github.com/streamlink/streamlink.git
  ref: f7be2514407ccda542f0d113066827d48414f09b
assets:
  ffmpeg-x86_64:
    filename: ffmpeg-n8.1.2-win64-gpl-8.1.zip
    url: https://github.com/streamlink/FFmpeg-Builds/releases/download/20260623-1/ffmpeg-n8.1.2-win64-gpl-8.1.zip
    sha256: a888bdb27894b93c4ab30eefca9e6fa0c82a6fb5a103696671b4449b36be2513
    type: zip
    sourcedir: ffmpeg-n8.1.2-win64-gpl-8.1
    targetdir: ffmpeg
    files:
      - from: bin/ffmpeg.exe
        to: ffmpeg.exe
      - from: LICENSE.txt
        to: LICENSE.txt
      - from: BUILDINFO.txt
        to: BUILDINFO.txt
builds:
  py314-x86_64:
    implementation: cp
    pythonversion: "3.14"
    platform: win_amd64
    pythonplatform: x86_64-pc-windows-msvc
    pythonembed:
      version: 3.14.6
      filename: python-v3.14.6-0-gc63aec69b-windows-x64-embed.zip
      url: https://github.com/streamlink/python-windows-embed/releases/download/20260617-1/python-v3.14.6-0-gc63aec69b-windows-x64-embed.zip
      sha256: 9563742df3af204c1d7d0d110716fe26c27b620a80d0f7f60f2be8c9f36b3fc6
    assets:
      - ffmpeg-x86_64
