app:
  name: streamlink
  rel: 1
git:
  repo: https://github.com/streamlink/streamlink.git
  ref: 8.5.0
assets:
  ffmpeg-x86_64:
    filename: ffmpeg-n8.1.2-win64-gpl-8.1.zip
    url: https://github.com/streamlink/FFmpeg-Builds/releases/download/20260623-1/ffmpeg-n8.1.2-win64-gpl-8.1.zip
    sha256: a888bdb27894b93c4ab30eefca9e6fa0c82a6fb5a103696671b4449b36be2513
    type: zip
    sourcedir: ffmpeg-n8.1.2-win64-gpl-8.1
    targetdir: ffmpeg
    files:
      - from: bin/ffmpeg.exe
        to: ffmpeg.exe
      - from: LICENSE.txt
        to: LICENSE.txt
      - from: BUILDINFO.txt
        to: BUILDINFO.txt
builds:
  py314-x86_64:
    implementation: cp
    pythonversion: "3.14"
    platform: win_amd64
    pythonplatform: x86_64-pc-windows-msvc
    pythonembed:
      version: 3.14.7
      filename: python-v3.14.7-0-g823f0323e-windows-x64-embed.zip
      url: https://github.com/streamlink/python-windows-embed/releases/download/20260806-1/python-v3.14.7-0-g823f0323e-windows-x64-embed.zip
      sha256: cc756129324440a976435a1dcf309634630075f053823e0a19799783f2dff248
    assets:
      - ffmpeg-x86_64
