name: Preview build
run-name: "Preview build - ${{ inputs.ref }}"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: A git ref on the Streamlink git repo
        default: master
        required: true
        type: string

jobs:
  build:
    name: "${{ inputs.ref }} (${{ matrix.build }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: installer
          - build: portable
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          ./install-build-dependencies.sh
      - name: Build
        run: |
          "./build-${{ matrix.build }}.sh" "" "" "${{ inputs.ref }}"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          path: dist/*
